# Generated by Django 5.2.7 on 2025-10-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='Téléphone', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=20, verbose_name='Nom de la marque')),
                ('logo', models.ImageField(upload_to='images_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=14)),
                ('image', models.ImageField(upload_to='', verbose_name='image_articles/')),
                ('stokcage', models.IntegerField(null=True)),
                ('ram', models.IntegerField(null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlesLiees', to='root.categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.marque')),
            ],
        ),
    ]
