# Generated by Django 5.2.7 on 2025-10-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='image_articles/'),
        ),
    ]
