# Generated by Django 5.2.7 on 2025-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_article_ram_alter_article_stokcage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image_articles/'),
        ),
    ]
