# Generated by Django 5.2.7 on 2025-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_article_image2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'verbose_name': 'Marque', 'verbose_name_plural': 'Marques'},
        ),
        migrations.AddField(
            model_name='article',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image_articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image1_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_articles/thumbnails/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image2_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_articles/thumbnails/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_articles/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modele',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAM (Go)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stokcage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stockage (Go)'),
        ),
    ]
