# Generated by Django 5.2.7 on 2025-11-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_article_options_alter_categorie_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(blank=True, default='Téléphone', max_length=32),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du client')),
                ('domaine', models.CharField(help_text="Domaine utilisé pour filtrer l'API publique", max_length=255, unique=True, verbose_name='Domaine (ex: https://client1.com)')),
                ('actif', models.BooleanField(default=True, verbose_name='Client actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Compte admin Django')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='root.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='root.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marque',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marques', to='root.client'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('client', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='marque',
            unique_together={('client', 'nom_marque')},
        ),
    ]
