# Generated by Django 5.2.7 on 2025-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_alter_categorie_nom_client_article_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domaine',
            field=models.URLField(unique=True),
        ),
    ]
