# Generated by Django 5.2.7 on 2025-12-04 10:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_client_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image1_thumbnail',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image2_thumbnail',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_thumbnail',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
